apiVersion: skaffold/v2beta5
kind: Config
deploy:
  kubectl:
    manifests:
      - './infra/k8s/*.yml'
build:
  local:
    push: false
  artifacts:
    - image: arun696/ticketauth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: '.'
